### ISSUE TITLE
可以添加服务器列表吗？

### ISSUE THREAD

**Issue by cfcboy** [heiher/sockstun#1]
多个服务器的情况下，可以点击选择。

**Comment by heiher** [comment]
好主意，现在对Android UI还不熟，得找时间研究一下。

**Comment by cfcboy** [comment]
v2rayng正常可以连接的socks5服务器，为啥你的软件连接不上。。。晕死。

**Comment by cfcboy** [comment]
感谢回复。

**Comment by heiher** [comment]
看看是不是用的UDP over UDP的Socks5服务端，但客户端选的确是UDP relay over TCP模式。

**Comment by cfcboy** [comment]
> 看看是不是用的UDP over UDP的Socks5服务端，但客户端选的确是UDP relay over TCP模式。

你好。打开或者关闭UDP relay over TCP，都连接不上。同一台服务器用V2rayNG正常。帮忙调试一下。谢谢

**Comment by heiher** [comment]
先确认一下连接的是不是Socks5协议的服务？可以先用curl测试一下:

```bash
curl -i --socks5-hostname [Socks Address]:[Socks Port] http://www.microsoft.com
```

**Comment by cfcboy** [comment]
> 先确认一下连接的是不是Socks5协议的服务？可以先用curl测试一下:
> 
> ```shell
> curl -i --socks5-hostname [Socks Address]:[Socks Port] http://www.microsoft.com
> ```

可以确认是socks5协议服务，一直在用。主要想试试你这个软件看速度性能各方面会不会好点。

**Comment by cfcboy** [comment]
我测试了安卓模拟器7.1和9.0都不能用。同种情况下V2rayNG正常使用。服务端确定是socks5协议。

**Comment by cfcboy** [comment]
自建xray服务端socks5协议，关闭UDP relay over TCP可以正常连接。。

**Comment by heiher** [comment]
请提供个可复现的环境或方法调试一下

**Comment by cfcboy** [comment]
> 请提供个可复现的环境或方法调试一下

服务器信息如何发送给你。

**Comment by heiher** [comment]
> 服务器信息如何发送给你。

email: r@hev.cc

**Comment by heiher** [comment]
确实无法使用，原因是服务端单端口多协议复用功能实现不能兼容Socks5握手信息的合并发送，返回了HTTP协议响应。

**Comment by cfcboy** [comment]
> 确实无法使用，原因是服务端单端口多协议复用功能实现不能兼容Socks5握手信息的合并发送，返回了HTTP协议响应。

谢谢测试。那你可以修复一下吗。很希望适用一下看看性能怎么样。

**Comment by heiher** [comment]
客户端是没有问题的，服务端需要修复，或换个正常的服务端。客户端采用合并发送不仅可以加快连接的建立速度（尤其在高延迟网络上），而且还可以在流量模型上帮助隐藏socks5协议的特征。

**Comment by cfcboy** [comment]
> 客户端是没有问题的，服务端需要修复，或换个正常的服务端。客户端采用合并发送不仅可以加快连接的建立速度（尤其在高延迟网络上），而且还可以在流量模型上帮助隐藏socks5协议的特征。

这个服务器端是收费的，服务商提供的。正常目前市面服务商都是提供这样的服务端。我测了好几家都不行。
你可以调试一下客户端做一下兼容吗？或者单独做一个兼容的按钮。可以手动选择或者自动判断

**Comment by heiher** [comment]
如果只是测试性能的话，要不先用xray服务端来跑，若是V2rayNG原本就能跑满线路的带宽的话，换客户端也不会有速度的上的改进，最多是设备节能一些。

或是作为消费者给服务提供商报兼容增强的需求，我也再想想有没有更好的无损兼容方法。

感谢您的反馈~

**Comment by cfcboy** [comment]
> 如果只是测试性能的话，要不先用xray服务端来跑，若是V2rayNG原本就能跑满线路的带宽的话，换客户端也不会有速度的上的改进，最多是设备节能一些。
> 
> 或是作为消费者给服务提供商报兼容增强的需求，我也再想想有没有更好的无损兼容方法。
> 
> 感谢您的反馈~

好的。谢谢了。期待你的好消息。对了。还有服务器列表增加一下，这个比较方便。不然多个服务器比较麻烦。一些功能可以参考V2rayNG，但是不用很复杂的功能，做好你的强项就行。

**Comment by heiher** [comment]
> 要不要我帮你写ui

欢迎PR

**Comment by cfcboy** [comment]
> 如果只是测试性能的话，要不先用xray服务端来跑，若是V2rayNG原本就能跑满线路的带宽的话，换客户端也不会有速度的上的改进，最多是设备节能一些。
> 
> 或是作为消费者给服务提供商报兼容增强的需求，我也再想想有没有更好的无损兼容方法。
> 
> 感谢您的反馈~

大佬你好。目前的1.1的版本还是无法使用服务商那边的代理。恳请大佬抽点时间看看能无损兼容吗，非常感谢。

**Comment by heiher** [comment]
> > 如果只是测试性能的话，要不先用xray服务端来跑，若是V2rayNG原本就能跑满线路的带宽的话，换客户端也不会有速度的上的改进，最多是设备节能一些。
> > 或是作为消费者给服务提供商报兼容增强的需求，我也再想想有没有更好的无损兼容方法。
> > 感谢您的反馈~
> 
> 大佬你好。目前的1.1的版本还是无法使用服务商那边的代理。恳请大佬抽点时间看看能无损兼容吗，非常感谢。

无损感觉不行，兼容这类不能正确处理流数据的服务端只能定制。
