### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by EmberHeartshine** [heiher/sockstun#21]
Have you considered submitting SocksTun to F-Droid or IzzyOnDroid?

**Comment by heiher** [comment]
No. Could you request to package it?

**Comment by linsui** [comment]
@heiher I can package this.

**Comment by heiher** [comment]
> @heiher I can package this.

Any progress?

**Comment by linsui** [comment]
Not yet, I'm waiting for your response. Can I package it for F-Droid?

**Comment by heiher** [comment]
> Not yet, I'm waiting for your response. Can I package it for F-Droid?

Of course. feel free to package it for F-Droid. Thank you.

**Comment by linsui** [comment]
Could you please upgrade the gradle so that it works with jdk 17? It's the default jdk on Debian bookworm.

**Comment by linsui** [comment]
@heiher I opened a PR for F-Droid packaging, can you take a look?

**Comment by heiher** [comment]
> @heiher I opened a PR for F-Droid packaging, can you take a look?

#26 Merged. Thank you. :+1:

**Comment by linsui** [comment]
Thanks! Can we have a new release?

**Comment by heiher** [comment]
> Thanks! Can we have a new release?

Done. https://github.com/heiher/sockstun/releases/tag/2.3

**Comment by linsui** [comment]
Another fix for reproducible build: https://github.com/heiher/sockstun/pull/27

**Comment by linsui** [comment]
Can you update the release apk with the above fix?

**Comment by heiher** [comment]
> Can you update the release apk with the above fix?

https://github.com/heiher/sockstun/releases/tag/2.4

**Comment by linsui** [comment]
Thanks! It will be published in a week. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15551

**Comment by heiher** [comment]
> Thanks! It will be published in a week. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15551

Great! Thank you.

**Comment by heiher** [comment]
@linsui Could you please update the app on F-Droid to version 2.5? Thanks.

**Comment by linsui** [comment]
It will be updated automatically. :)

**Comment by heiher** [comment]
> It will be updated automatically. :)

Nice! Thanks. :)
