### ISSUE TITLE
按照文档无法在windows上完成编译，缺少<lwip/tcp.h>头文件

### ISSUE THREAD

**Issue by Joehaivo** [heiher/sockstun#24]
按照文档
1. git clone --recursive https://github.com/heiher/sockstun sockstun2 正常
2. cd .\sockstun2\ 正常
3. .\gradlew assembleDebug

以下是详细信息：
PS D:\workspace\sockstun2> .\gradlew assembleDebug
Starting a Gradle Daemon (subsequent builds will be faster)
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'sockstun2', project ':app'
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: 意外的元素 (uri:"", local:"base-extension")。所需元素为<{}codename>,<{}layoutlib>,<{}api-level>

> Task :app:externalNativeBuildDebug FAILED
Build hev-socks5-tunnel_armeabi-v7a
D:/workspace/sockstun2/app/src/main/jni/hev-socks5-tunnel/src/hev-socks5-session-tcp.c:13:10: fatal error: 'lwip/tcp.h' file not found
#include <lwip/tcp.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [D:/android/sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:476: D:/workspace/sockstun2/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/hev-socks5-tunnel/src/hev-socks5-session-tcp.o] Error 1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process D:\android\sdk\ndk\21.4.7075529\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\workspace\sockstun2\app\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\workspace\sockstun2\app\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-24 NDK_OUT=D:/workspace/sockstun2/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\workspace\sockstun2\app\build\intermediates\ndkBuild\debug\lib hev-socks5-tunnel}
  [armeabi-v7a] Compile thumb  : hev-socks5-tunnel <= hev-socks5-session-tcp.c

  D:/workspace/sockstun2/app/src/main/jni/hev-socks5-tunnel/src/hev-socks5-session-tcp.c:13:10: fatal error: 'lwip/tcp.h' file not found
  #include <lwip/tcp.h>
           ^~~~~~~~~~~~
  1 error generated.
  make: *** [D:/android/sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:476: D:/workspace/sockstun2/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/hev-socks5-tunnel/src/hev-socks5-session-tcp.o] Error 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
12 actionable tasks: 12 executed

**Comment by heiher** [comment]
符合预期，Windows文件系统不支持符号链接，而子模块中包含。可以使用GitHub Action来构建，只需Fork项目，并创建一个发布即可触发，完成后会自动上传到发布页。
