### ISSUE TITLE
请问一下使用时的问题

### ISSUE THREAD

**Issue by ycdgod1** [heiher/sockstun#25]
socks address是自己的socks5服务器和要连接的端口号吗
下面的用户名和密码就是自己服务器的用户名和密码吗

**Comment by heiher** [comment]
> socks address是自己的socks5服务器和要连接的端口号吗 下面的用户名和密码就是自己服务器的用户名和密码吗

是的。

**Comment by ycdgod1** [comment]
> > socks address是自己的socks5服务器和要连接的端口号吗 下面的用户名和密码就是自己服务器的用户名和密码吗
> 
> 是的。

非常感谢您的回答
