### ISSUE TITLE
Proxy failed

### ISSUE THREAD

**Issue by HotYounger** [heiher/sockstun#29]
Hello, I am a nativ file compiled from your source code. When I use it in my project, I use global mode,If you enable disabling yourself, you can successfully proxy, otherwise you cannot.
If the following code is added, the proxy will succeed; otherwise, the proxy will fail
        String selfName = getApplicationContext().getPackageName();
            try {
                builder.addDisallowedApplication(selfName);
            } catch (NameNotFoundException e) {
                e.printStackTrace();
            }

**Comment by heiher** [comment]
Bypass VPN application itself is required because the upstream sockets are not marked as protected.

**Comment by HotYounger** [comment]
> 绕过 VPN 应用程序本身是必需的，因为上游套接字未标记为受保护。

ok
