### ISSUE TITLE
Not work socket 5 via proxy SSH

### ISSUE THREAD

**Issue by OmlineEditor** [heiher/sockstun#40]
I use ConnectBot (SSH and local shell client) https://f-droid.org/en/packages/org.connectbot/

I connect to SSH and create a dynamic socket 5 tunnel in this program (use 127.0.0.1:8080).
The tunnel works in the browser, but not in your program.

**Comment by heiher** [comment]
As expected, the socks5 server needs to support UDP for domain resolution, which SSH does not support.

**Comment by heiher** [comment]
Refer: https://github.com/heiher/sockstun/issues/62
