### ISSUE TITLE
Disconnects on network failure 

### ISSUE THREAD

**Issue by john-d13** [heiher/sockstun#46]
As subject reads.  When the network connection LTE or WiFi disconnects , socks tun VPN Connection disconnects.  

Need to reopen sockstun app to reconnect.

**Comment by heiher** [comment]
I can't reproduce it.

1. Enable sockstun. (include browser app)
2. Start browser.
3. Turn off Wifi.
4. Turn on Wifi.
5. Refresh browser page.

**Comment by john-d13** [comment]
Check my video

https://drive.google.com/file/d/17f2qAwpUzJGW5FnWJpQtIvvHRKsGPOLX/view?usp=sharing

**Comment by john-d13** [comment]
sorry you can close,  its an issue with appium.
