### ISSUE TITLE
Not showing in apps section on Android TV

### ISSUE THREAD

**Issue by vitos1k** [heiher/sockstun#47]
Hey! Thanks alot for this app! It's super usefull!
One question though, it isn't showing in APPS section in android TV, so i can't add it to favorits for easy access?
The app shows in settings -> apps -> all apps -> looong list of apps, most of them are daemons or background apps

Thanks anyway

**Comment by heiher** [comment]
Try this: https://github.com/heiher/sockstun/actions/runs/11992738944 (artifacts will expire in one day)

**Comment by vitos1k** [comment]
> Try this: https://github.com/heiher/sockstun/actions/runs/11992738944 (artifacts will expire in one day)

Oh wow! That worked like a charm!!!

**Comment by heiher** [comment]
> > Try this: https://github.com/heiher/sockstun/actions/runs/11992738944 (artifacts will expire in one day)
> 
> Oh wow! That worked like a charm!!! Thank you very much!!!1

Thank you for your feedback. I'll merge it.
