### ISSUE TITLE
 'lwip/init.h' file not found

### ISSUE THREAD

**Issue by saaam000** [heiher/sockstun#5]
I have cloned the project and tried to run it in android studio but I'm encountering "File not found" for these two lines from "\sockstun\app\src\main\jni\hev-socks5-tunnel\src\hev-main.c" : 

#include <lwip/init.h>
#include <lwip/priv/tcp_priv.h>

I have cloned it as you mentioned in readme.md : 
> git clone --recursive https://github.com/heiher/sockstun

**Comment by heiher** [comment]
The submodules are not compatible with Windows, and the workaround is replace symbolic link with real files.
