### ISSUE TITLE
Problems with DNS

### ISSUE THREAD

**Issue by gxosty** [heiher/sockstun#54]
Hello, I provide 8.8.8.8 as DNS address for IPv4, but dns queries aren't processed. My server supports UDP ASSOCIATE and I checked it with different socks5 client. Even if I pass different valid addresses like 1.1.1.1, 76.76.10.0, 8.8.4.4, it doesn't work. I am sure I didn't enable UDP-relay-over-TCP option. What might be the problem? Or do DNS queries not go through UDP ASSOCIATE?

**Comment by heiher** [comment]
Which socks5 server are you using?

**Comment by gxosty** [comment]
> Which socks5 server are you using?

I am running [Chisel](https://github.com/jpillora/chisel) server on another machine.

**Comment by gxosty** [comment]
Turns out the problem is in the server itself... I apologize for not double checking it. Thank you, you can close the issue

**Comment by heiher** [comment]
Refer: https://github.com/heiher/sockstun/issues/62
