### ISSUE TITLE
Not working on real device.

### ISSUE THREAD

**Issue by evgenybozhko2** [heiher/sockstun#6]
Hello, dear creator this useful lib. Thank you for your job. But I was faced with the issue when no traffic pass on a real device. It works perfectly on an emulator. Do you know where is the problem?

**Comment by heiher** [comment]
check udp relay over tcp?

**Comment by evgenybozhko2** [comment]
Config from you repository app.

misc:
  task-stack-size: 20480
tunnel:
  mtu: 8500
socks5:
  port: 1080
  address: 'XXX.153.XXX.183'
  udp: 'tcp'
  username: 'username'
  password: 'password'

**Comment by evgenybozhko2** [comment]
Apk 1.3 version from releases not pass traffic as well.

**Comment by heiher** [comment]
The socks5 server needs to support udp relay. I think you should try sockstun with this socks5 server: https://github.com/heiher/hev-socks5-server

**Comment by evgenybozhko2** [comment]
> I believe that `sockstun` works with `hev-socks5-server`, so let's try it first. Then we can replace components or modify the configuration to troubleshoot the issue.

Yep, you right. It works like charm with hev-socks5-server. Thank you a lot for this greatest job.
