### ISSUE TITLE
fatal error: 'lwip/tcp.h' file not found

### ISSUE THREAD

**Issue by xfliyy** [heiher/sockstun#8]
![tun error](https://github.com/heiher/sockstun/assets/15180105/47522f5d-d8cf-4c22-94c6-e8686810c702)

**Comment by heiher** [comment]
??

**Comment by xfliyy** [comment]
> ？？

不好意思 打扰了，上面传错图了 我想问一下这个项目是不是对NDK跟Gradle版本有要求   我clone后使用android studio打开，但是编译不过 Gradle 5.4.1 插件3.3.3 NDK 21.4.7075529
![tun error](https://github.com/heiher/sockstun/assets/15180105/da2f5e0d-1716-4e83-90dd-b37ad7723695)
