### ISSUE TITLE
能支持x86吗

### ISSUE THREAD

**Issue by mosentest** [heiher/sockstun#9]
？？？如题

**Comment by mosentest** [comment]
还有能支持http、https协议么，对这块了解不深入

**Comment by mosentest** [comment]
2001:4860:4860::8888

dns ipv6是固定这个么

**Comment by mosentest** [comment]
hev-htproxy 这个项目不维护了吗 config是返回什么信息，能说下吗

**Comment by heiher** [comment]
1. x86是可以支持的，考虑到x86设备比较少，就没在Android Makefile中默认启用编译。
2. 目前只支持socks5协议，其它http、https代理协议不支持。
3. DNS IPv6不是固定的，可以指定其它DNS服务地址。
4. hev-htproxy不再维护了。

**Comment by heiher** [comment]
Resolved by https://github.com/heiher/sockstun/commit/6701cbee8d9692cee44fd477bf653b6fcd81e0f4
